name: Build, Push Docker Image, Scan, and Trigger Helm Update

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.name }}
        password: ${{ secrets.secret }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.name }}/compasstreinamento:latest

    - name: Log out from Docker Hub
      run: docker logout

  scan:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy

    - name: Scan Docker image with Trivy
      run: trivy image ${{ secrets.name }}/cprojetocompass:latest

  trigger-helm-update:
    runs-on: ubuntu-latest
    needs: scan
    steps:
    - name: Trigger Helm Update Workflow
      uses: peter-evans/repository-dispatch@v3
      with:
        repository: julianobcgato/helm-repo
        token: ${{ secrets.gittoken }}
        event-type: update-helm
        client-payload: '{"docker_image": "${{ secrets.secret }}/projetocompass:latest"}'

