name: CI/CD Pipeline

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/julianobcgato/projetocompass:${{ github.run_number }}
          load: false
          no-cache: false
          pull: false
          github-token: ${{ secrets.token2 }}

  alterar_tag:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: juliano/projetocompass
          token: ${{ secrets.secret }}

      - name: Set run number
        run: echo "RUN_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Modify yaml File
        run: |
          sed -i "s/^      tag: .*/      tag: $RUN_NUMBER/" ./julianoapi/values.yaml

      - name: Cat values.yaml to verify changes
        run: cat ./julianoapi/values.yaml

      - name: Commit and Push Changes
        run: |
          git config user.name "Juliano"
          git config user.email "julianobcgato@gmail.com"
          git add ./julianoapi/values.yaml
          git commit -m "Update image tag in values.yaml"
          git push
