name: CI/CD Pipeline

on:
  push:
    paths-ignore:
      - '**.md' 
    branches:
      - master
  release:
    types: [created]

jobs:
  build-and-push:
     runs-on: ubuntu-22.04
     steps:
     - name: Login to Docker Hub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.name}}
         password: ${{ secrets.secret }}
          
     - uses: actions/checkout@v2
      
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: '3.x'
      
     - name: Build and push Docker image
       uses: docker/build-push-action@v2
       with:
         context: .
         push: true
         tags: julianobcgato/projetocompass:${{ github.run_number }}
         
  alterar_tag:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: julianobcgato/code
          token: ${{ secrets.segredops }}

      - name: Set run number
        run: echo "RUN_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Cat deployment.yaml to verify changes
        run: cat ./gitops/deployment.yaml

      - name: ls deployment.yaml to verify changes
        run: ls 
        
      - name: Modify yaml File
        run: |
          sed -i "s/^        image: .*/        image: julianobcgato\/projetocompass:$RUN_NUMBER/" ./gitops/deployment.yaml

      - name: Commit and Push Changes
        run: |
          git config user.name "Juliano"
          git config user.email "julianobcgato@gmail.com"
          git add ./gitops/deployment.yaml
          git commit -m "Update image tag in values.yaml"
          git push

  scan:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy

    - name: Scan Docker image with Trivy
      run: trivy image ${{ secrets.name }}/compasstreinamento:latest
