name: SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          java-package: jdk
          check-latest: false
          server-id: github
          server-username: ${{ secrets.name }}
          server-password: ${{ secrets.secret }}
          overwrite-settings: true

      - name: Build and analyze on SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.sonartoken }}
          run: |
            mvn clean install
            mvn sonar:sonar \
            -Dsonar.projectKey=projetocompass \
            -Dsonar.organization=julianobcgato \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$sonartoken
